### ISSUE TITLE
PostActivationPostPaid not returning a result

### ISSUE THREAD

**Issue by rjheeta** [phoneboxcad/API-Issue-Tracking-Only#1]
Hi Gary

I supplied the following data, and cannot get PostActivationPostPaid to work. Can you please advise if there are any incorrect or missing fields?

`{'simcardOrder': 'false', 'simcard_no': '89302720523100138225', 'startDate': '2020-10-28', 'endDate': '', 'planId': 771, 'firstName': 'BRAD', 'lastName': 'PURCELL', 'email': 'pb-orders@freeside.eyesurf.ca', 'serviceType': '', 'portin_carrier': '', 'portin_accountNo': '', 'portin_phoneNo': '', 'portin_other': '', 'service_countryId': '42', 'service_province': 'ON', 'service_city': 'CAMBRIDGE', 'delivery_countryId': '', 'delivery_province': '', 'delivery_address': '', 'delivery_postal': '', 'prorateDataCap': '1.94 GB', 'prorateEndDate': 'Nov 01, 2020', 'proratePct': 0.16, 'prorate_duration': 'Oct 28, 2020~Nov 01, 2020', 'currency': 'CAD', 'simcard_fee': 0.0, 'charge_duration': 'Nov 02, 2020~Dec 01, 2020', 'plan_fee': 75.0, 'gst_rate': 13.0, 'pst_rate': 0.0, 'gst_amt': 11.32, 'pst_amt': 0.0, 'subtotal': 87.1, 'promocode': 'EyeSurf', 'promocredit': 0.0, 'total': 98.42, 'bizId': 3072}`

Thanks

**Comment by Magic-Jay** [comment]
needed to update issue using template.
