### ISSUE TITLE
PostActivationPostPaid is returning 0 upon what appears to be successful input

### ISSUE THREAD

**Issue by rjheeta** [phoneboxcad/API-Issue-Tracking-Only#2]
**Describe the issue**
What are you trying to achieve: 

Attempting to submit an activation via **PostActivationPostPaid**; however, I am getting 0 as the result code

**API Documentation used**
Details about the API documentations:
1. What is the ``URL`` to the API documentation you followed: 
https://developer.gophonebox.com/APIReference/ActivationServices/PostActivationInfoPostpaid.html

2. What is the last updated date(located on the lower right corner of the page) of the document: 
LastUpdated: 10/30/2020, 12:48:28 AM

**To Reproduce**
1. What ``API service`` are you using: 
Partner API

2. What is the ``endpoint URL``: 
https://testmyaccount.azurewebsites.net/api/Activation/PostActivationInfoPostpaid

3. What is the ``request method``: 
Activation/PostActivationInfoPostpaid

4. What is the ``request header``: 

Just `client` (eyesurf) and `apitoken` (which changes)
5. What is the ``request parameter``: 

None

6. What is the ``request body`` (__please format in JSON and use code highlight__): 

`{'simcardOrder': 'false', 'simcard_no': '89302720523100138225', 'startDate': '2020-10-28', 'endDate': '', 'planId': 771, 'firstName': 'BRAD', 'lastName': 'PURCELL', 'email': 'pb-orders@freeside.eyesurf.ca', 'serviceType': '', 'portin_carrier': '', 'portin_accountNo': '', 'portin_phoneNo': '', 'portin_other': '', 'service_countryId': '42', 'service_province': 'ON', 'service_city': 'CAMBRIDGE', 'delivery_countryId': '', 'delivery_province': '', 'delivery_address': '', 'delivery_postal': '', 'prorateDataCap': '1.94 GB', 'prorateEndDate': 'Nov 01, 2020', 'proratePct': 0.16, 'prorate_duration': 'Oct 28, 2020~Nov 01, 2020', 'currency': 'CAD', 'simcard_fee': 0.0, 'charge_duration': 'Nov 02, 2020~Dec 01, 2020', 'plan_fee': 75.0, 'gst_rate': 13.0, 'pst_rate': 0.0, 'gst_amt': 11.32, 'pst_amt': 0.0, 'subtotal': 87.1, 'promocode': 'EyeSurf', 'promocredit': 0.0, 'total': 98.42, 'bizId': 3072}`

7. What is the ``actual request code`` (__please use code highlight__)

Wasn't clear on this one? 

**Expected Response**
What is the expected ``success response`` returned from the ``API request``(__please format in JSON and use code highlight__):  

Expected that a non-zero integer would be returned.

**Actual Response**
What is the actual ``response`` returned from the ``API request``(__please format in JSON and use code highlight__):

0 is returned

**Comment by Magic-Jay** [comment]
resolved.
