### ISSUE TITLE
CohortGo PostActivationInfoPrepaid request always non-successful

### ISSUE THREAD

**Issue by gizotti** [phoneboxcad/API-Issue-Tracking-Only#3]
**Describe the issue**
What are you trying to achieve: 

I am trying to order a sim card in the test environment using the CohortGo credentials but the Post Prepaid ActivationInfo endpoint always return a `0` referenceID which the documentation shows as Non-Success.

**API Documentation used**
Details about the API documentations:
1. What is the ``URL`` to the API documentation you followed: 
https://developer.gophonebox.com/APIReference/ActivationServices/PostActivationInfoPrepaid.html#post-prepaid-activationinfo

2. What is the last updated date(located on the lower right corner of the page) of the document: 
11/5/2020, 2:36:22 AM

**To Reproduce**
1. What ``API service`` are you using: 
Post Prepaid ActivationInfo

2. What is the ``endpoint URL``: 
`https://testmyaccount.azurewebsites.net/api/Activation/PostActivationInfoPrepaid`

3. What is the ``request method``: 
POST

4. What is the ``request header``: 
```
"Accept"=>"*/*"
"Content-Length"=>"670"
"Content-Type"=>"application/json"
"User-Agent"=>"rest-client/2.1.0 (linux-gnu x86_64) ruby/2.6.6p146"
"apitoken"=>"/ksOaNeF2EiZziUJTLUtR5le9mNMqkYa"
"client"=>"2950"
```
5. What is the ``request parameter``: 
No parameters

6. What is the ``request body`` (__please format in JSON and use code highlight__): 
```javascript
{"simcardOrder":true,"simcard_no":"","startDate":"2020-12-23","endDate":"","serviceType":"","service_countryId":42,"service_province":"BC","service_city":"Toronto","firstName":"Gabriel Test","lastName":"Smith","email":"sim-notifications+162@cohortgo.com","portin_carrier":"","portin_account":"","portin_phoneNo":"","portin_other":"","planId":849,"plan_fee":40.0,"promocode":"","bizId":2950,"currency":"CAD","simcard_fee":10.0,"gst_rate":5.0,"pst_rate":7.0,"gst_amt":2.5,"pst_amt":3.5,"promocredit":0.0,"subtotal":50.0,"total":56.0,"delivery_countryId":35,"delivery_province":"SP","delivery_city":"Rio Claro","delivery_address":"Rua 4 n35","delivery_postal":"123123-123"}
```

7. What is the ``actual request code`` (__please use code highlight__)

**Expected Response**
What is the expected ``success response`` returned from the ``API request``(__please format in JSON and use code highlight__):  

A valid succesful `referenceID`

**Actual Response**
What is the actual ``response`` returned from the ``API request``(__please format in JSON and use code highlight__):
`0`

**Comment by Magic-Jay** [comment]
``endDate`` value was not correctly given in the doc, updated the doc. 

``endDate = startDate + PlanTypeD - 1``
